name: build project

on:
  push:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]


jobs: 
  build-code:
    runs-on: ubuntu-latest
    container: unityofdisaster/node-with-angular
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: lint code
        run: yarn lint
      - name: run unit tests
        run: yarn test
      - name: build project
        run: yarn build
